# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set work directory
WORKDIR /app

# Copy project
COPY . /app

# Install dependencies and the package
RUN pip install --no-cache-dir .

# Default command to run the MCP server
CMD ["mcp-open-data-hk"]
