name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Release Notes
        run: |
          # Generate release notes from commit history
          echo "## What's Changed" > RELEASE-NOTES.md
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo HEAD~1)..HEAD >> RELEASE-NOTES.md || echo "* Minor fixes and improvements" >> RELEASE-NOTES.md

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body_path: RELEASE-NOTES.md
          draft: false
          prerelease: false